# Generated by Django 5.0.1 on 2024-01-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Students',
        ),
    ]
