# Generated by Django 5.0.1 on 2024-01-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0002_rename_teachers_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Users',
        ),
    ]
